version: "3.1"

services:
  redis:
    image: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
     - storebackend_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5678:5672"
      - "45678:15672"
    networks:
      - storebackend_network

volumes:
  redis_data:


networks:
  storebackend_tris-web:
    external: true