version: "3.1"

services:
  redis:
    image: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
     - network1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5678:5672"
      - "45678:15672"
    networks:
      - network1

  mysql:
    image: mysql:8.4
    restart: always
    environment :
      MYSQL_ROOT_PASSWORD : 'asd123'
    ports:
      - "3307:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - network1

volumes:
  redis_data:
  mysql_db:

networks:
  network1:
    name: storebackend_tris-web
    external: true