version: "3.1"

services:
  redis:
    image: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
     - network1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5678:5672"
      - "45678:15672"
    networks:
      - network1

volumes:
  redis_data:


networks:
  network1:
    name : storebackend_tris-web
    external: true